TimeStamp: "2018-10-18 10:09:23"
Address: "Shenzhen"
Postcode: 51804
CompanyInfomation:
  Name: "Sunny"
  MarketCapitalization: 500000
  EmployeeNum: 500
  Department:
    - "Finance"
    - "Design"
    - "Program"
    - "Sales"
  IsOpen: false
  Time: 1m30s

